name: Bug
description: File a bug report
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Beschreibung
    validations:
      required: true
  - type: checkboxes
    id: urgent
    attributes:
      label: Urgent-Ticket
      description: Verhindert der Bug das Weiterarbeiten und ist eine schnellstmögliche Lösung zu finden?
      options:
        - label: Urgent?
          required: false
