name: Bug
description: File a bug report
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Beschreibung
    validations:
      required: true
  - type: checkboxes
    id: urgent
    attributes:
      label: Urgentticket
      description: Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.
      options:
        - label: Ist Urgentticket.
          required: false
