name: Bug
description: File a bug report
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Beschreibung
    validations:
      required: true
  - type: checkboxes
    id: urgent
    attributes:
      label: Urgentbug
      description: Muss der Bug schnellstmoeglich gefixed werden?
      options:
        - label: Urgent?
